"""initial schema

Revision ID: 4f38179b82e3
Revises: 
Create Date: 2026-08-29 21:52:05.032471
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# GUID and JSONType are defined by the application, not by SQLAlchemy.
import app.db


revision = '4f38179b82e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_ref', sa.String(length=32), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=False),
    sa.Column('applicant_name_hint', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('analysis_version', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('rules_version', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_case_ref'), ['case_ref'], unique=True)
        batch_op.create_index('ix_cases_status_created', ['status', 'created_at'], unique=False)

    op.create_table('applicant_profiles',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('fields', app.db.JSONType(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicant_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applicant_profiles_case_id'), ['case_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('case_id', app.db.GUID(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', app.db.JSONType(), nullable=False),
    sa.Column('analysis_version', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('rules_version', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_case_action', ['case_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)

    op.create_table('discrepancies',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=96), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=96), nullable=True),
    sa.Column('comparison_method', sa.String(length=32), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('candidate_payload', app.db.JSONType(), nullable=False),
    sa.Column('reasoner_payload', app.db.JSONType(), nullable=True),
    sa.Column('verification_payload', app.db.JSONType(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('rules_version', sa.String(length=64), nullable=True),
    sa.Column('review_decision', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discrepancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discrepancies_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_discrepancies_case_severity', ['case_id', 'severity'], unique=False)

    op.create_table('documents',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=48), nullable=False),
    sa.Column('document_subtype', sa.String(length=96), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_readable', sa.Boolean(), nullable=False),
    sa.Column('quality_flags', app.db.JSONType(), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_documents_case_type', ['case_id', 'document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('reports',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('analysis_snapshot', app.db.JSONType(), nullable=False),
    sa.Column('report_json', app.db.JSONType(), nullable=False),
    sa.Column('overall_status', sa.String(length=32), nullable=True),
    sa.Column('docx_path', sa.String(length=1024), nullable=True),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('qa_passed', sa.Boolean(), nullable=True),
    sa.Column('qa_errors', app.db.JSONType(), nullable=False),
    sa.Column('regenerated_count', sa.Integer(), nullable=False),
    sa.Column('analysis_version', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('rules_version', sa.String(length=64), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_case_id'), ['case_id'], unique=False)

    op.create_table('validation_results',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=96), nullable=False),
    sa.Column('rule_category', sa.String(length=48), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('field', sa.String(length=96), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', app.db.JSONType(), nullable=False),
    sa.Column('rules_version', sa.String(length=64), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index('ix_validation_case_result', ['case_id', 'result'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_case_id'), ['case_id'], unique=False)

    op.create_table('document_pages',
    sa.Column('document_id', app.db.GUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.Column('tables', app.db.JSONType(), nullable=False),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_per_document')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    op.create_table('evidence',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('discrepancy_id', app.db.GUID(), nullable=True),
    sa.Column('document_id', app.db.GUID(), nullable=True),
    sa.Column('document_name', sa.String(length=512), nullable=True),
    sa.Column('document_type', sa.String(length=48), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=96), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('bbox', app.db.JSONType(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_discrepancy_id'), ['discrepancy_id'], unique=False)

    op.create_table('extractions',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('document_id', app.db.GUID(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=48), nullable=True),
    sa.Column('requested_fields', app.db.JSONType(), nullable=False),
    sa.Column('payload', app.db.JSONType(), nullable=False),
    sa.Column('pages_used', app.db.JSONType(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extractions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extractions_document_id'), ['document_id'], unique=False)

    op.create_table('field_values',
    sa.Column('case_id', app.db.GUID(), nullable=False),
    sa.Column('document_id', app.db.GUID(), nullable=False),
    sa.Column('extraction_id', app.db.GUID(), nullable=True),
    sa.Column('field_name', sa.String(length=96), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('bbox', app.db.JSONType(), nullable=True),
    sa.Column('document_type', sa.String(length=48), nullable=True),
    sa.Column('id', app.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_values', schema=None) as batch_op:
        batch_op.create_index('ix_field_values_case_field', ['case_id', 'field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_values_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_values_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_values_field_name'), ['field_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_values_field_name'))
        batch_op.drop_index(batch_op.f('ix_field_values_document_id'))
        batch_op.drop_index(batch_op.f('ix_field_values_case_id'))
        batch_op.drop_index('ix_field_values_case_field')

    op.drop_table('field_values')
    with op.batch_alter_table('extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extractions_document_id'))
        batch_op.drop_index(batch_op.f('ix_extractions_case_id'))

    op.drop_table('extractions')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_discrepancy_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_results_case_id'))
        batch_op.drop_index('ix_validation_case_result')

    op.drop_table('validation_results')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_case_id'))

    op.drop_table('reports')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index('ix_documents_case_type')
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    with op.batch_alter_table('discrepancies', schema=None) as batch_op:
        batch_op.drop_index('ix_discrepancies_case_severity')
        batch_op.drop_index(batch_op.f('ix_discrepancies_case_id'))

    op.drop_table('discrepancies')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))
        batch_op.drop_index('ix_audit_case_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('applicant_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applicant_profiles_case_id'))

    op.drop_table('applicant_profiles')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_status_created')
        batch_op.drop_index(batch_op.f('ix_cases_case_ref'))

    op.drop_table('cases')
    # ### end Alembic commands ###
